// <auto-generated />
using System;
using System.Collections.Generic;

using System.Globalization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace BadDragonAPI.Data
{
    public partial class ProductList
    {
        [JsonProperty("sku")]
        public string Sku { get; set; }

        [JsonProperty("name")]
        public string Name { get; set; }
    }

    public partial class ProductList
    {
        public static ProductList[] FromJson(string json) => JsonConvert.DeserializeObject<ProductList[]>(json, BadDragonAPI.Data.ConverterProductList.Settings);
    }

    internal static class ConverterProductList
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}
